### ISSUE TITLE
how to log the req.body?

### ISSUE THREAD

**Issue by GuilhermeMedeiros** [pinojs/pino-http#37]
I already have my own serializer but req.body is empty.

**Comment by mcollina** [comment]
the body is parsed after, so it won't be included. You need to put the body-parser before the pino-http middleware, because the serializer is applied to the request when the child logger is created.

I would recommend against including the body in the child logger, but rather log that separately at a lower log level. A body could be **massive**, so you might log tens of megabytes multiple times.

**Comment by GuilhermeMedeiros** [comment]
yeah that makes sense! thanks!

**Comment by Jeff-Tian** [comment]
> I would recommend against including the body in the child logger, but rather log that separately at a lower log level. A body could be **massive**, so you might log tens of megabytes multiple times.

Can you share an example of how to log them in **lower log level**?

**Comment by mcollina** [comment]
wherever in your code/middleware, do `req.log.debug({ body: req.body })`

**Comment by maricn** [comment]
@mcollina Is there a way to set it up so that request body is logged in the `req` object every time log level lower than `INFO` is used?

I've seen we can use this to add it to req object:
```js
        serializers: {
          req(req) {
            req.body = req.raw.body;
            return req;
          },
        },
```
But that will be used for any log level invocation of logger.

And in case we want to specify that per-invocation, we can't put it in the context in the `req` object because it will overwrite it.

**Comment by mcollina** [comment]
You’d need to write some custom code for that :/
